"""
Django settings for BugManage project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this files, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+*(q#h_c$n(__-yj%p$33j#^!13un(fs2-rn6=_mny70oxw+h!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SMS',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware.auth.AuthMiddleware',
]

ROOT_URLCONF = 'BugManage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BugManage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Tracer',
        'USER': 'root',
        'PASSWORD': '77582358991',
        'HOST': 'db',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# 配置文件Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 1000,
                "encoding": 'utf-8'
            },
            'SOCKER_TIMEOUT': 10,
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# datetime.datetime.now() / datetime.datetime.utcnow()  => utc时间
# TIME_ZONE = 'UTC'

# datetime.datetime.now() - 上海东八区时间 / datetime.datetime.utcnow()  => utc时间
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 影响自动生成数据库时间字段
#    USE_TZ = True , 创建UTC时间写入到数据库
#    USE_TZ = False, 根据TIME_ZONE设置的时区进行创建时间并写入数据库
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# 白名单，没有登录都可以访问的URL
WHITE_REGEX_URL_LIST = [
    "/register/",
    "/send/sms/",
    "/login/",
    "/image/code/",
    "/index/",
    "/login/sms/",
    "/price/",
]

# 騰訊雲短信應用的app_id
TENCENT_SMS_APP_ID = 1400369143
# 騰訊雲短信應用的 app_key
TENCENT_SMS_APP_KEY = "84418dd98abd7cf42107dedb4093c3b8"
# 騰訊雲短信籤名內容
TENCENT_SMS_SIGN = "代碼and詩"

TENCENT_SMS_TEMPLATE = {
    'register': 641424,
    'login': 641422,
}

# 腾讯COS的ID和KEY
TENCENT_COS_ID = "AKIDylQ6XiKBFBuT7epJtFOK4whFZQ2NoI9j"
TENCENT_COS_KEY = "hAPTIr9WeV6XjfLlCNK0Wnoc9vXu2rRu"


ALI_GATEWAY = "https://openapi.alipaydev.com/gateway.do"
ALI_PRI_KEY_PATH = os.path.join(BASE_DIR, 'files/私钥.txt')
ALI_PUB_KEY_PATH = os.path.join(BASE_DIR, 'files/支付宝公钥.txt')
ALI_NOTIFY_URL = "http://127.0.0.1:8000/pay/notify"
ALI_RETURN_URL = "http://127.0.0.1:8000/pay/notify"
ALI_APPID = "2021000117637762"
